version: 2.1
orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.2.0
  heroku: circleci/heroku@2.0.0
jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test
  publish:
    docker:
      - image: cimg/node:16.10
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    environment:
      IMAGE_NAME: jieromu79/cont_integration    
    steps:
      - checkout
      - setup_remote_docker
      - run: 
         name: Publish Docker Image to Docker Hub
         command: |
           echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
           docker build -t $IMAGE_NAME:<< pipeline.git.tag >>.
           docker push $IMAGE_NAME:<< pipeline.git.tag >>
  deploy:
      docker:
          - image: cimg/node:16.10
      steps:
          - setup_remote_docker      
          - heroku/install
          - checkout
          - run:
              name: Heroku Container Push
              command: | 
                  heroku container:login
                  heroku container:push web -a jerome-su-devops
                  heroku container:release web -a jerome-su-devops

workflows:
  simple_workflow:
    jobs:
      - build:
          filters: 
              branches:
                only: main
      - test:
          requires:
              - build
          filters: 
              branches:
                only: main
          
      - publish:
          requires:
            - test
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
      - deploy:
          requires:
            - publish
          filters: 
            tags:
              only: /^v\d.0{1}.0{1}$/
            branches:
              ignore: /.*/
